/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ContextMenu: typeof import('./../components/ContextMenu.vue')['default']
    Dashboard: typeof import('./../components/Dashboard.vue')['default']
    DashboardFinished: typeof import('./../components/Dashboard-finished.vue')['default']
    FileList: typeof import('./../components/FileList.vue')['default']
    FileModal: typeof import('./../components/FileModal.vue')['default']
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    Navbar: typeof import('./../components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UploadResource: typeof import('./../components/UploadResource.vue')['default']
  }
}
